version: '3'

services:
  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: service
      POSTGRES_PASSWORD: service_password
      POSTGRES_DB: hyperchess
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - "6379:6379"